name: Auto CLang format

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['master']

jobs:
  clang-format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - uses: akopachov/clang-format-action@main
      with:
        style: file

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: CLang format changes
        branch: ${{ github.head_ref }}