name: Auto CLang format

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['master']
    paths: ['**.c', '**.h']

jobs:
  clang-format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        submodules: 'recursive'

    - name: CLang format
      run: ./clang-format-all.ps1
      shell: pwsh

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: CLang format changes